[build]
  command = "chmod +x netlify/build.sh && netlify/build.sh"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"
  PRISMA_GENERATE_DATAPROXY = "true"
  DATABASE_URL = "${env:DATABASE_URL}"

# Redirection pour les routes API
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true 